[package]
name = "file-logging"
version = "0.1.0"
authors = ["pfried <philipsfried@gmail.com>"]

[dependencies]
log = "0.3"

[dependencies.log4rs]
version = "0.4"
features = ["yaml"]

[dependencies.log4rs-rolling-file]
version = "0.1"
features = ["gzip"]
