
refresh_rate: 5 seconds

appenders:
  stdout:
    kind: console
    filters:
      -
        kind: threshold
        level: error
    encoder:
      kind: pattern
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {l} {M} {m}{n}"

  file:
    kind: rolling_file
    path: logs/example.log
    encoder:
      kind: pattern
      pattern: "{d} {l} {M} {m}{n}"
    trigger:
      kind: size
      limit: 4 kb
    roller:
      kind: fixed_window
      count: 5
      pattern: archive/example-{}.gz

root:
  level: trace
  appenders:
    - stdout
    - file

